name: Tests for Library

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:

  Tests-library:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Install latest CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install ninja-build g++-14 cmake libboost-all-dev
      
      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Version Cmake
        run: cmake --version
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure
        run: | 
           mkdir build
           cmake \
            -S . \
            -B build \
            -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: | 
           cmake --build build --config Release --target all

      - name: Run tests
        run: |
          cd build/tests
          ctest -VV --output-on-failure 

      - name: Test install
        run: |          
          sudo cmake --build build --config Release --target install